name: flutter_flavorizr
description: A flutter utility to easily create flavors in your flutter application
version: 2.4.1
repository: https://github.com/AngeloAvv/flutter_flavorizr
issue_tracker: https://github.com/AngeloAvv/flutter_flavorizr/issues
homepage: https://www.angelocassano.it

environment:
  sdk: ">=3.0.0 <4.0.0"

funding:
  - https://github.com/sponsors/AngeloAvv

platforms:
  android:
  ios:
  macos:

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.0
  args: ^2.4.2
  checked_yaml: ^2.0.3
  collection: ^1.18.0
  image: ^4.1.7
  io: ^1.0.4
  json_annotation: ^4.8.1
  mason_logger: ^0.3.3
  sprintf: ^7.0.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
