name: flutter_flavorizr
description: A flutter utility to easily create flavors in your flutter application
version: 1.0.1
repository: https://github.com/AngeloAvv/flutter_flavorizr
issue_tracker: https://github.com/AngeloAvv/flutter_flavorizr/issues
homepage: https://www.angelocassano.it

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^2.0.11
  checked_yaml: ^1.0.0
  io: ^0.3.4
  json_annotation: ^3.0.1
  xml: ^3.6.1
  yaml: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
